Update ManualTrigger.yaml

diff --git a/.github/workflows/ManualTrigger.yaml b/.github/workflows/ManualTrigger.yaml
--- a/.github/workflows/ManualTrigger.yaml
+++ b/.github/workflows/ManualTrigger.yaml
@@ -3,24 +3,23 @@ name: Manual Trigger Workflow
 on:
   workflow_dispatch:
     inputs:
-      environment:
-        description: 'Environment for deployment'
+      sourcebranch:
+        description: 'Source Branch Name'
+        type: string
         required: true
-        default: 'production'
-      repository1:
-        description: 'Global Repository'
-        required: true
-      repository2:
-        description: 'Regional Repository'
-        required: true
-      reference:
-        description: 'Version To Deploy Global REpository'
+      tragetbranch:
+        description: 'Target Branch Name'
+        type: string
         required: true
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
-
+    environment: develop
+    env:
+      TARGET_ENVIRONMENT: ${{inputs.tragetbranch}}
+      SOURCE_REPO: ${{inputs.sourcebranch}}
+   # if: env.TARGET_ENVIRONMENT == 'develop'
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -46,35 +45,36 @@ jobs:
         uses: actions/checkout@v2
         with:
           repository: vishklearning/test2
-          path: ./force-app
+          path: ./test2-1
           ref: main
-
-      # Checkout the second repository
+      # ${{ env.SOURCE_REPO }}
+      
       - name: Checkout Repository 2
         uses: actions/checkout@v2
         with:
           repository: vishklearning/Demo-SF-GH
-          path: ./force-app
+          path: ./Demo-SF-GH-1
           ref: master
-
-#      # Run the MergeDX
-#       - name: MergerDX
-#         id: MergerDX
-#         continue-on-error: true
-#         run: |
-#           python3 ./acct-scripts/mergerDX/merger.py merge_delta -s ${{github.head_ref}} -t ${{github.base_ref}} -a ${{secrets.API_VERSION}}
-#           if [ $? -eq 0 ] && [ $(ls srcToDeploy | wc -l) -ne 0 ]; then
-#             echo "Success in MergeDX"
-#             zip -r srcToDeploy.zip ./srcToDeploy/
-#             git rev-parse --verify HEAD
-#           else 
-#             echo "::warning:: Failure in MergeDX: The srcToDeploy.zip is EMPTY(i.e. No New Code Changes Detected)"
-#             exit 1
-#           fi
-      # Create Directory
-      - name: Create Directory
+      # ${{ env.TARGET_REPO }} 
+        
+     # Run the MergeDX
+      - name: MergerDX
+        id: MergerDX
+        continue-on-error: true
         run: |
-          mkdir destforceapp
+          python3 ./acct-scripts/mergerDX/merger.py merge_delta -s ${{env.SOURCE_REPO}} -t ${{env.TARGET_REPO}} -a ${{secrets.API_VERSION}}
+          if [ $? -eq 0 ] && [ $(ls srcToDeploy | wc -l) -ne 0 ]; then
+            echo "Success in MergeDX"
+            zip -r srcToDeploy.zip ./srcToDeploy/
+            git rev-parse --verify HEAD
+          else 
+            echo "::warning:: Failure in MergeDX: The srcToDeploy.zip is EMPTY(i.e. No New Code Changes Detected)"
+            exit 1
+          fi
+#       # Create Directory
+#       - name: Create Directory
+#         run: |
+#           mkdir destforceapp
           
 #       - name: Merge Repository 1
 #         run: |
