Update ManualTrigger.yaml

diff --git a/.github/workflows/ManualTrigger.yaml b/.github/workflows/ManualTrigger.yaml
--- a/.github/workflows/ManualTrigger.yaml
+++ b/.github/workflows/ManualTrigger.yaml
@@ -67,6 +67,21 @@ jobs:
           path: ./test2
           ref: develop
       # ${{ env.TARGET_REPO }}
+
+      # Run the MergeDX
+      - name: MergerDX
+        id: MergerDX
+        continue-on-error: true
+        run: |
+          python3 ./acct-scripts/mergerDX/merger.py merge_delta -s ${{github.head_ref}} -t ${{github.base_ref}} -a ${{secrets.API_VERSION}}
+          if [ $? -eq 0 ] && [ $(ls srcToDeploy | wc -l) -ne 0 ]; then
+            echo "Success in MergeDX"
+            zip -r srcToDeploy.zip ./srcToDeploy/
+            git rev-parse --verify HEAD
+          else 
+            echo "::warning:: Failure in MergeDX: The srcToDeploy.zip is EMPTY(i.e. No New Code Changes Detected)"
+            exit 1
+          fi
       
        # Authenticate SFDX Instance
       - name: Authticate the URL
